In [2]:
%config Completer.use_jedi = False

In [3]:
import pandas as pd
import scipy.stats as stats
import numpy as np

In [4]:
df_bnf = pd.read_csv('bonferroni.csv')
df_bnf.head()

,Unnamed: 0,X,sws_rs,sws_gb,sws_ms,sws_fa,sws_rw,sws_total
0,1,zALFF_17Networks_1,NaN,NaN,NaN,0.000748,NaN,NaN
1,2,zReHo_17Networks_LH_SomMotA_5,NaN,NaN,0.032759,NaN,NaN,NaN
2,3,zfALFF_rHipp_L,0.048210,NaN,NaN,NaN,NaN,0.026329
3,4,zfALFF_mAmyg_L,NaN,NaN,NaN,NaN,NaN,0.037395
4,5,zfALFF_17Networks_RH_ContA_PFCl_4,0.049117,NaN,NaN,NaN,NaN,NaN

In [69]:
df_all = pd.read_csv('df_measurements.csv')
df_all.head()

,Subject_ID,sws_rw,sws_rs,zReHo_lPFtha_R,zReHo_lPFtha_L,zReHo_cTtha_R,zReHo_cTtha_L,zReHo_Otha_R,zReHo_Otha_L,zReHo_PPtha_R,...,zReHo_17Networks_RH_DorsAttnA_SPL_3,zReHo_17Networks_RH_DorsAttnA_SPL_2,zReHo_17Networks_RH_DorsAttnA_SPL_1,zReHo_17Networks_RH_DorsAttnA_ParOcc_3,zReHo_17Networks_RH_DorsAttnA_ParOcc_2,zReHo_17Networks_RH_DorsAttnA_ParOcc_1,zReHo_17Networks_RH_DorsAttnA_TempOcc_3,zReHo_17Networks_RH_DorsAttnA_TempOcc_2,zReHo_17Networks_RH_DorsAttnA_TempOcc_1,zReHo_17Networks_RH_SomMotB_Cent_3
0,sub-0015,3.4,1.666667,-0.680650,-0.740437,-0.698144,-0.650759,-0.733759,-0.700806,-0.594061,...,0.632937,0.484317,0.878408,0.776844,0.120077,0.906160,1.010050,0.325154,0.070342,0.635567
1,sub-0085,2.8,2.166667,-0.607122,-0.614975,-0.431298,-0.432305,-0.471722,-0.649952,-0.509859,...,1.272547,0.551014,1.482868,1.110642,0.290340,0.240267,0.374478,-0.029872,-0.361664,0.516531
2,sub-0134,3.8,2.000000,-0.263834,-0.493474,-0.278857,-0.294843,-0.368193,-0.633978,-0.544125,...,0.510567,0.323151,0.741446,0.395507,0.640683,0.381234,0.707233,0.149791,-0.279489,0.050742
3,sub-0152,4.0,1.666667,0.258873,0.978757,0.155146,0.000891,0.075672,-0.116517,-0.169480,...,-0.357383,-0.159408,0.082269,0.183071,-0.415082,-0.233840,-0.117080,0.584565,0.458543,0.246564
4,sub-0260,3.8,2.500000,-0.338928,-0.980045,-0.135230,-0.253972,-0.105502,-0.099361,-0.202247,...,0.387290,0.171799,0.892404,0.532177,0.216433,0.554115,0.634269,0.389356,-0.211930,0.565683

In [70]:
df_all.shape

(118, 1935)

In [ ]:
lst = df_bnf['X']

In [ ]:
df_selected = pd.DataFrame()
for col in df_all.columns:
    for item in lst:
        if col == item:
            print(col)
            #df_selected[col] = df_all[col]

In [ ]:
df_selected = pd.read_csv('df_selected.csv')

In [ ]:
df_selected.head()

In [ ]:
df = pd.read_csv('../../csv files/df_allSleepADHD_30May2022.csv')

In [ ]:
df.head()

In [ ]:
#df_selected['id'] = [idx.split('-')[1] for idx in df_selected['Subject_ID']]

In [ ]:
df_selected['id'] = df_selected['Subject_ID']

In [ ]:
df_selected[['id1', 'id2']] = df_selected['id'].str.split('-',expand=True)

In [ ]:
df_selected["id_number"] = df_selected["id2"].apply(pd.to_numeric)

In [ ]:
df_selected.drop(['id', 'id1', 'id2'], axis = 1, inplace=True)

In [ ]:
df2 = pd.merge(left = df, right = df_selected, how = 'left', on = 'id_number' )

In [ ]:
df2.drop(['Unnamed: 0', 'level_0', 'index'], axis = 1, inplace = True)
df2.head()

In [ ]:
df_wave = pd.read_csv('CompareConnDich.csv')
df_wave.head()

In [ ]:
df_wave['id_number'] = df_wave['id_number'].astype('int')

In [ ]:
df_wave.head()

In [ ]:
df3 = pd.merge(left = df2, right=df_wave[['id_number','imaging waves']], how = 'left', on = 'id_number')

In [ ]:
df3.head()

In [ ]:
#df = df3.dropna(subset = ['imaging waves'])
df = df3

## converting sws scores to categorical

In [ ]:
df['sws_gb'] = np.nan
df['sws_fa'] = np.nan
df['sws_ms'] = np.nan
df['sws_rs'] = np.nan
df['sws_rw'] = np.nan
df['sws_total'] = np.nan

In [ ]:
for i,wave in enumerate(df['imaging waves']):
    if wave == 'ses-wave2':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_gb_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_fa_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_ms_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rs_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rw_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_total_40')]
        
    elif wave == 'ses-wave3':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_gb_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_fa_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_ms_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rs_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rw_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_total_40')]

## converting adhd scores to categorical

In [ ]:
df['cpadhd_raw'] = np.nan

In [ ]:
for i,wave in enumerate(df['imaging waves']):
    if wave == 'ses-wave2':
        df.iloc[i, df.columns.get_loc('cpadhd_raw')] = df.iloc[i, df.columns.get_loc('p4_cpadhdi_raw')]
        
    elif wave == 'ses-wave3':
        df.iloc[i, df.columns.get_loc('cpadhd_raw')] = df.iloc[i, df.columns.get_loc('p5_cpadhdi_raw')]

In [ ]:
df[['p4_cpadhdi_raw', 'p5_cpadhdi_raw', 'cpadhd_raw']]

In [ ]:
df.to_csv('BrainBehaviour_1June2022.csv')

## converting all 6 sws to categ based on waves

In [ ]:
df = pd.read_csv('BrainBehaviour_1June2022.csv')

- sws_gb_40

In [ ]:
df['dich_sws_gb_40'] = np.nan
df['dich_sws_fa_40'] = np.nan
df['dich_sws_ms_40'] = np.nan
df['dich_sws_rs_40'] = np.nan
df['dich_sws_rw_40'] = np.nan
df['dich_sws_total_40'] = np.nan

In [ ]:
for i,wave in enumerate(df['imaging waves']):
    if wave == 'ses-wave2':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_gb_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_fa_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_ms_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rs_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rw_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_total_40')]
        
    elif wave == 'ses-wave3':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_gb_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_fa_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_ms_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rs_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rw_40')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_40')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_total_40')]

- sws_gb_60

In [ ]:
df['dich_sws_gb_60'] = np.nan
df['dich_sws_fa_60'] = np.nan
df['dich_sws_ms_60'] = np.nan
df['dich_sws_rs_60'] = np.nan
df['dich_sws_rw_60'] = np.nan
df['dich_sws_total_60'] = np.nan

In [ ]:
for i,wave in enumerate(df['imaging waves']):
    if wave == 'ses-wave2':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_gb_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_fa_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_ms_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rs_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rw_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_total_60')]
        
    elif wave == 'ses-wave3':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_gb_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_fa_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_ms_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rs_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rw_60')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_60')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_total_60')]

- sws_gb_65

In [ ]:
df['dich_sws_gb_65'] = np.nan
df['dich_sws_fa_65'] = np.nan
df['dich_sws_ms_65'] = np.nan
df['dich_sws_rs_65'] = np.nan
df['dich_sws_rw_65'] = np.nan
df['dich_sws_total_65'] = np.nan

In [ ]:
for i,wave in enumerate(df['imaging waves']):
    if wave == 'ses-wave2':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_gb_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_fa_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_ms_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rs_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rw_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_total_65')]
        
    elif wave == 'ses-wave3':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_gb_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_fa_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_ms_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rs_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rw_65')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_65')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_total_65')]

- sws_gb_70

In [ ]:
df['dich_sws_gb_70'] = np.nan
df['dich_sws_fa_70'] = np.nan
df['dich_sws_ms_70'] = np.nan
df['dich_sws_rs_70'] = np.nan
df['dich_sws_rw_70'] = np.nan
df['dich_sws_gb_70'] = np.nan
df['dich_sws_fa_70'] = np.nan
df['dich_sws_ms_70'] = np.nan
df['dich_sws_rs_70'] = np.nan
df['dich_sws_rw_70'] = np.nan
df['dich_sws_total_70'] = np.nan

In [ ]:
for i,wave in enumerate(df['imaging waves']):
    if wave == 'ses-wave2':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_gb_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_fa_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_ms_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rs_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_rw_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c4_sws_total_70')]
        
    elif wave == 'ses-wave3':
        df.iloc[i, df.columns.get_loc('dich_sws_gb_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_gb_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_fa_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_fa_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_ms_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_ms_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_rs_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rs_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_rw_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_rw_70')]
        df.iloc[i, df.columns.get_loc('dich_sws_total_70')] = df.iloc[i, df.columns.get_loc('dich_tscore_c5_sws_total_70')]

- sws fa,ms,rs,rw,total for 40,60,65,70

In [ ]:
num = ['40','60','65','70']
sws = ['fa','ms','rs','rw','total']

In [ ]:
len(num)

In [ ]:
df2 = df

In [ ]:
df2.shape

In [ ]:
for i,n in enumerate(num):
    for j,s in enumerate(sws):
        name = 'dich_sws_' + sws[j] + '_' + num[i]
        df[name] = np.nan
        #print(name)

In [ ]:
for i,wave in enumerate(df['imaging waves']):

    if wave == 'ses-wave2':
        for k in range(len(num)):
            for j in range(len(sws)):
                name = 'dich_sws_' + sws[j] + '_' + num[k]
                name2 = 'dich_tscore_c4_sws_' +sws[j] + '_' + num[k]
                df.iloc[i, df.columns.get_loc(name)] = df.iloc[i, df.columns.get_loc(name2)]
    elif wave == 'ses-wave3':
        for k in range(len(num)):
            for j in range(len(sws)):
                name = 'dich_sws_' + sws[j] + '_' + num[k]
                name3 = 'dich_tscore_c5_sws_'+ sws[j] + '_' + num[k]
                df.iloc[i, df.columns.get_loc(name)] = df.iloc[i, df.columns.get_loc(name3)]

- cpadhd categ for waves

In [ ]:
num = ['40','60','65','70']

In [ ]:
for i in range(len(num)):

    name = 'dich_cpadhd_' + num[i]
    df[name] = np.nan
    #print(name)

In [ ]:
for i,wave in enumerate(df['imaging waves']):

    if wave == 'ses-wave2':
        for k in range(len(num)):
            for j in range(len(sws)):
                name = 'dich_cpadhd_' + num[k]
                name2 = 'dich_tscore_p4_cpadhd_'+ num[k]
                df.iloc[i, df.columns.get_loc(name)] = df.iloc[i, df.columns.get_loc(name2)]
    elif wave == 'ses-wave3':
        for k in range(len(num)):
            for j in range(len(sws)):
                name = 'dich_cpadhd_' + num[k]
                name3 = 'dich_tscore_p5_cpadhd_'+ num[k]
                df.iloc[i, df.columns.get_loc(name)] = df.iloc[i, df.columns.get_loc(name3)]

In [ ]:
df.to_csv('tst.csv')

In [ ]:
df.to_csv('BrainBehaviour_2June2022.csv')

## adding all subscales of sws in form of 4060 to dataframe

In [67]:
df = pd.read_csv('BrainBehaviour_2June2022.csv')
df.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis = 1, inplace = True)
df.head()

,id_number,ChildGender,d1_diagadhd_dich,d3_diagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,c4_sws_gb,...,dich_sws_gb_70,dich_sws_fa_70,dich_sws_ms_70,dich_sws_rs_70,dich_sws_rw_70,dich_sws_total_70,dich_cpadhd_40,dich_cpadhd_60,dich_cpadhd_65,dich_cpadhd_70
0,15,1,0.0,0,0.0,0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,85,0,0.0,0,0.0,5,14.0,0.0,1.0,2.8,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,134,1,0.0,0,0.0,2,0.0,0.0,0.0,3.6,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,152,0,1.0,0,1.0,7,2.0,2.0,3.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,307,0,0.0,0,0.0,0,2.0,1.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [62]:
sws = ['fa','ms','rs','rw','total']

In [46]:
for j,s in enumerate(sws):
    name = 'dich_tscore_sws_' + sws[j] 
    name2 = 'dich_tscore_sws_' + sws[j] 
    df[name] = np.nan
    df[name2] = np.nan
    #print(name)

In [73]:
sws = ['fa','ms','rs','rw','total']
for i,wave in enumerate(df['imaging waves']):
    for j in range(len(sws)):
        if wave == 'ses-wave2':
            name1 = 'dich_sws_' + sws[j] + '_4060'
            df[name1] = np.nan
            name2 = 'tscore_c4_sws_' + sws[j]
            for k,ind in enumerate(df[name2]):
                if df[name2][k] >= 60:
                    df[name1][k] = '1'
                elif df[name2][k] <= 40:
                    df[name1][k] = '0'
    
        elif wave == 'ses-wave3':
            name1 = 'dich_sws_' + sws[j] + '_4060'
            df[name1] = np.nan
            name2 = 'tscore_c5_sws_' + sws[j]
            for k,ind in enumerate(df[name2]):
                if df[name2][k] >= 60:
                    df[name1][k] = '1'
                elif df[name2][k] <= 40:
                    df[name1][k] = '0'

<ipython-input-73-63fc3f5a0252>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name1][k] = '0'
<ipython-input-73-63fc3f5a0252>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name1][k] = '1'
<ipython-input-73-63fc3f5a0252>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name1][k] = '0'
<ipython-input-73-63fc3f5a0252>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name1][k] = '1'

In [78]:
df.to_csv('BrainBehaviour_8June2022.csv')

In [77]:
df

,id_number,ChildGender,d1_diagadhd_dich,d3_diagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,c4_sws_gb,...,dich_sws_total_70,dich_cpadhd_40,dich_cpadhd_60,dich_cpadhd_65,dich_cpadhd_70,dich_sws_fa_4060,dich_sws_ms_4060,dich_sws_rs_4060,dich_sws_rw_4060,dich_sws_total_4060
0,15,1,0.0,0,0.0,0,0.0,0.0,0.0,3.0,...,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,1.0,NaN
1,85,0,0.0,0,0.0,5,14.0,0.0,1.0,2.8,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,134,1,0.0,0,0.0,2,0.0,0.0,0.0,3.6,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,152,0,1.0,0,1.0,7,2.0,2.0,3.0,3.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,NaN,1.0,0.0
4,307,0,0.0,0,0.0,0,2.0,1.0,0.0,3.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,7019,1,0.0,0,0.0,0,NaN,2.0,0.0,3.8,...,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
102,7020,0,0.0,0,0.0,4,0.0,1.0,0.0,3.2,...,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
103,7069,0,0.0,1,NaN,8,6.0,3.0,7.0,3.6,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0
104,7074,0,1.0,0,0.0,7,4.0,2.0,4.0,3.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN
105,7148,1,0.0,1,1.0,12,10.0,12.0,6.0,3.4,...,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,1.0